name: Main Service CI/CD Pipeline

on:
  push:
    paths:
        - "backend/**"

jobs:

  commit-short: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short github.sha
        run: echo "COMMIT_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

  test-and-lint:
    needs: commit-short
    strategy:
        fail-fast: false
        matrix:
            service:
                - { name: "backend", service_dir: "backend"}
    uses: ./.github/workflows/lint-test.yml
    with:
        service_name: ${{ matrix.service.name}}
        service_dir: ${{ matrix.service.service_dir}}
        commit_short: ${{ env.COMMIT_SHORT }}
        options: "install"
    secrets: inherit

  build-app-docker-image:
    needs: test-and-lint
    strategy:
        fail-fast: false
        matrix:
            service:
                - { name: "backend", service_dir: "backend"}
    uses: ./.github/workflows/build-app-docker.yml
    with:
        service_name: ${{ matrix.service.name}}
        service_dir: ${{ matrix.service.service_dir}}
        commit_short: ${{ env.COMMIT_SHORT }}
    secrets: inherit

