name: Main Service CI/CD Pipeline

on:
  push:
    paths:
        - "backend/**"

jobs:

  test-and-lint:
    strategy:
        fail-fast: false
        matrix:
            service:
                - { name: "backend", service_dir: "backend"}
    uses: ./.github/workflows/lint-test.yml
    with:
        service_name: ${{ matrix.service.name}}
        service_dir: ${{ matrix.service.service_dir}}
        commit_short: ${{ steps.extract_commit.outputs.commit_short }}
    secrets: inherit

  build-app-docker-image:
    needs: test-and-lint
    strategy:
        fail-fast: false
        matrix:
            service:
                - { name: "backend", service_dir: "backend"}
    uses: ./.github/workflows/build-app-docker.yml
    with:
        service_name: ${{ matrix.service.name}}
        service_dir: ${{ matrix.service.service_dir}}
        commit_short: ${{ steps.extract_commit.outputs.commit_short }}
    secrets: inherit

  extract-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Get the commit short hash
        id: extract_commit
        run: |
          echo "::set-output name=commit_short::$(git rev-parse --short=7 $GITHUB_SHA)"
