name: Backend Service CI/CD Pipeline

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:

  setup-context:
    runs-on: ubuntu-latest
    steps:

      - name: Set commit short
        run: echo "COMMIT_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    outputs:
      commit_short: ${{ env.COMMIT_SHORT }}

  test-and-lint:
    needs: setup-context
    strategy:
      fail-fast: false
      matrix:
        service:
          - { name: "backend", service_dir: "backend" }
    uses: ./.github/workflows/lint-test.yml
    with:
      service_name: ${{ matrix.service.name }}
      service_dir: ${{ matrix.service.service_dir }}
      commit_short: ${{ needs.setup-context.outputs.commit_short }}
      options: "install"
    secrets: inherit

  build-app-docker-image:
    needs: [test-and-lint, setup-context]
    strategy:
      fail-fast: false
      matrix:
        service:
          - { name: "backend", service_dir: "backend" }
    uses: ./.github/workflows/build-app-docker.yml
    with:
      service_name: ${{ matrix.service.name }}
      service_dir: ${{ matrix.service.service_dir }}
      commit_short: ${{ needs.setup-context.outputs.commit_short }}
    secrets: inherit
